### ISSUE TITLE
Return an empty collection instead of null in `ExerciseController`

### ISSUE THREAD

**Issue by mepox** [mepox/fitbuddy#104]
[Sonar issue link](https://sonarcloud.io/project/issues?issues=AYQT58-2wxsCzz419tCS&open=AYQT58-2wxsCzz419tCS&id=fitbuddy-app)

Compliant solution: `return Collections.emptyList();`

https://github.com/mepox/fitbuddy/blob/d8129e004d8d9632bfe9fa4aca52fa117961f9c5/src/main/java/app/fitbuddy/operation/controller/ExerciseController.java#L56-L66

**Comment by hrandhawa13** [comment]
Can I work on it?
