### ISSUE TITLE
Return an empty collection instead of null in `HistoryController`

### ISSUE THREAD

**Issue by mepox** [mepox/fitbuddy#107]
[Sonar issue link](https://sonarcloud.io/project/issues?issues=AYQT58_GwxsCzz419tCe&open=AYQT58_GwxsCzz419tCe&id=fitbuddy-app)

Compliant solution: `return Collections.emptyList();`

https://github.com/mepox/fitbuddy/blob/6a7c29712cf8ef43515191a907809f154314db68/src/main/java/app/fitbuddy/operation/controller/HistoryController.java#L63-L81

**Comment by gaurav9777** [comment]
Can I solve this issue?
