### ISSUE TITLE
Add unit tests for `readMany` method in `src/main/java/app/fitbuddy/jpa/service/crud/AppUserCrudService.java`

### ISSUE THREAD

**Issue by mepox** [mepox/fitbuddy#109]
https://github.com/mepox/fitbuddy/blob/c3551654303f4d155a4c007f87178ece3b396af2/src/main/java/app/fitbuddy/jpa/service/crud/AppUserCrudService.java#L69-L76

Add the tests to the end of `src/test/java/app/fitbuddy/jpa/service/crud/AppUserCrudServiceTest.java`, in a new `@Nested` class, same as the other tests.

**Comment by SwethaTamatam** [comment]
@mepox , I would like to work on this issue.

**Comment by mepox** [comment]
> @mepox , I would like to work on this issue.can you assign it to me.
> 

Hi @SwethaTamatam ! Sure go ahead. If you have any questions let me know.

Note there are TestHelper classes which you can use in src/test/java/app/fitbuddy/testhelper

**Comment by SwethaTamatam** [comment]
sure.
