### ISSUE TITLE
Show a status/feedback when there is an error/exception on the user page

### ISSUE THREAD

**Issue by mepox** [mepox/fitbuddy#116]
Currently there are no feedbacks on the following events for the user (only in the console log):

Exercise page:
- Adding a new exercise but the exercise name already exists
- Changing an exercise name but the new name already exists
- Trying to delete an exercise which is already in use in the history

Account page:
- Old password not correct
- Old password not valid
- New password not valid
- New password and confirm new password doesnt match.

Messages are provided by the backend as a response text.

Working (simple) example on the Login and Register page. They are good starting point.

I created an empty div with id:
https://github.com/mepox/fitbuddy/blob/f24a386fecce7cba685cffd7dd3ef758af0fefcf/src/main/resources/static/public/register.html#L38-L39

Updating the div based on the status:
https://github.com/mepox/fitbuddy/blob/f24a386fecce7cba685cffd7dd3ef758af0fefcf/src/main/resources/static/public/js/register.js#L31-L37

Function defined here, which is also included in the user's page (home.html):
https://github.com/mepox/fitbuddy/blob/f24a386fecce7cba685cffd7dd3ef758af0fefcf/src/main/resources/static/public/js/commons.js#L1-L10

**Comment by aishakapan** [comment]
Hey mepox. was trying to reproduce some errors and I see what you mean on Exercise page, but not sure what is the difference between Old password not correct vs. valid? I assume not valid means stuff like not meeting the character count? Also noticed that when the new user password and confirm password aren't matching it tells me "Registered successfully", might be a separate backend issue. Anyway, let me know and I'll be happy to crack on with this!

**Comment by mepox** [comment]
> Hey mepox, so I was trying to reproduce some errors and I see what you mean on Exercise page, but not sure what is the difference between Old password not correct vs. valid? I assume not valid means stuff like not meeting the character count? Also noticed that when the new user password and confirm password aren't matching it tells me "Registered successfully", might be a separate backend issue. Anyway, let me know and I'll be happy to crack on with this!

Hi @aishakapan ! Thanks for taking your time to review it.

Good catch 😅 I opened an issue for the bug #161 

You are right re "not correct vs valid". Maybe I could use different wording?
- When users provide a wrong old password then it's "not correct".
- When the password doesn't pass the validation then it's "not valid". 

Right now the backend only checks for character count.

Validations are done by annotations in the DTO classes:
Registering:
https://github.com/mepox/fitbuddy/blob/cfe6212802cd58aee7d7984e2280e99a9ef8d28a/src/main/java/app/fitbuddy/dto/RegisterDTO.java
Changing password on account page:
https://github.com/mepox/fitbuddy/blob/cfe6212802cd58aee7d7984e2280e99a9ef8d28a/src/main/java/app/fitbuddy/dto/accountinfo/AccountInfoUpdateDTO.java
