### ISSUE TITLE
Remove `public` modifiers in `src/test/java/app/fitbuddy/operation/service/NewUserServiceTest.java`

### ISSUE THREAD

**Issue by mepox** [mepox/fitbuddy#125]
[Sonar issue link](https://sonarcloud.io/project/issues?fileUuids=AYR6f4c05oK9VB3SF-pi&resolved=false&rules=java%3AS5786&id=fitbuddy-app&open=AYR6f4rh5oK9VB3SF-pn)

https://github.com/mepox/fitbuddy/blob/e9c013c333b5a65c42758cd7eca38f1e3196bb89/src/test/java/app/fitbuddy/operation/service/NewUserServiceTest.java#L28

https://github.com/mepox/fitbuddy/blob/e9c013c333b5a65c42758cd7eca38f1e3196bb89/src/test/java/app/fitbuddy/operation/service/NewUserServiceTest.java#L35

https://github.com/mepox/fitbuddy/blob/e9c013c333b5a65c42758cd7eca38f1e3196bb89/src/test/java/app/fitbuddy/operation/service/NewUserServiceTest.java#L44

https://github.com/mepox/fitbuddy/blob/e9c013c333b5a65c42758cd7eca38f1e3196bb89/src/test/java/app/fitbuddy/operation/service/NewUserServiceTest.java#L53

https://github.com/mepox/fitbuddy/blob/e9c013c333b5a65c42758cd7eca38f1e3196bb89/src/test/java/app/fitbuddy/operation/service/NewUserServiceTest.java#L71

**Comment by haseeb-xd** [comment]
I'll do it

**Comment by mepox** [comment]
Hi @haseeb-xd ! There will be a big refactor coming soon, so please don't work on this issue. Sorry!

**Comment by haseeb-xd** [comment]
> Hi @haseeb-xd ! There will be a big refactor coming soon, so please don't work on this issue. Sorry!

Alright

**Comment by mepox** [comment]
Hi @haseeb-xd ! Project refactor is done now, finally. You still would like to do this issue?
