### ISSUE TITLE
Add `@NotNull` to `PathVariable` in `src/main/java/app/fitbuddy/controller/crud/HistoryController.java`

### ISSUE THREAD

**Issue by mepox** [mepox/fitbuddy#139]
**Add `@NotNull` to `PathVariable`:**

https://github.com/mepox/fitbuddy/blob/292283120e0ca13c8d44acc4e44ea14bbb8acab8/src/main/java/app/fitbuddy/controller/crud/HistoryController.java#L80

https://github.com/mepox/fitbuddy/blob/292283120e0ca13c8d44acc4e44ea14bbb8acab8/src/main/java/app/fitbuddy/controller/crud/HistoryController.java#L92

**Solution:**
```@PathVariable("id") @NotNull Integer historyId```

**Then the null checks can be safely removed in:**
https://github.com/mepox/fitbuddy/blob/292283120e0ca13c8d44acc4e44ea14bbb8acab8/src/main/java/app/fitbuddy/controller/crud/HistoryController.java#L82

https://github.com/mepox/fitbuddy/blob/292283120e0ca13c8d44acc4e44ea14bbb8acab8/src/main/java/app/fitbuddy/controller/crud/HistoryController.java#L94

**After removing the if statement, correct the indentation.**

**Comment by haseeb-xd** [comment]
will do it
