### ISSUE TITLE
`LoginService` should use `LoginDTO`

### ISSUE THREAD

**Issue by mepox** [mepox/fitbuddy#175]
**`LoginService` should use `LoginDTO` instead of Strings:**
https://github.com/mepox/fitbuddy/blob/7db6b55100f91e1bc8cd0e896a75935d63cc3040/src/main/java/app/fitbuddy/service/operation/LoginService.java#L40

**Update the login method code (at 3 places?) to use the LoginDTO fields.**

**`LoginController` needs to be updated:**
https://github.com/mepox/fitbuddy/blob/7db6b55100f91e1bc8cd0e896a75935d63cc3040/src/main/java/app/fitbuddy/controller/operation/LoginController.java#L33

**Tests needs to be updated too.**

**`LoginServiceTest`:**
https://github.com/mepox/fitbuddy/blob/7db6b55100f91e1bc8cd0e896a75935d63cc3040/src/test/java/app/fitbuddy/service/operation/LoginServiceTest.java#L37
https://github.com/mepox/fitbuddy/blob/7db6b55100f91e1bc8cd0e896a75935d63cc3040/src/test/java/app/fitbuddy/service/operation/LoginServiceTest.java#L47

**`LoginControllerTest` (use `loginDtoMock` in Line 36):**
https://github.com/mepox/fitbuddy/blob/7db6b55100f91e1bc8cd0e896a75935d63cc3040/src/test/java/app/fitbuddy/controller/operation/LoginControllerTest.java#L43

**Comment by iravimandalia** [comment]
Hi @mepox, assign this issue to me. I'm working on it.
