### ISSUE TITLE
Remove `currentUserId` null check in `src/main/java/app/fitbuddy/controller/crud/AppUserController.java`

### ISSUE THREAD

**Issue by mepox** [mepox/fitbuddy#176]
This is an unnecessary null check.

https://github.com/mepox/fitbuddy/blob/7db6b55100f91e1bc8cd0e896a75935d63cc3040/src/main/java/app/fitbuddy/controller/crud/AppUserController.java#L53-L61

Then we can remove the `Integer currentUserId` and pass the `Id` using `appUserPrincipal.getId()` to `appUserCrudService.update` method directly.

**Comment by iravimandalia** [comment]
Hi @mepox, assign this issue to me. I'm working on it.
