### ISSUE TITLE
Code refactor in `ExerciseController`

### ISSUE THREAD

**Issue by mepox** [mepox/fitbuddy#184]
We are creating unnecessary variables for `userId` in the `ExerciseController` methods, for example:
https://github.com/mepox/fitbuddy/blob/b911c38ae8f614682bfb996f49eaed03cb66c197/src/main/java/app/fitbuddy/controller/crud/ExerciseController.java#L37-L38
At the above, we could pass the `userId` directly:
`exerciseRequestDTO.setAppUserId(appUserPrincipal.getId());`

Same in the other methods:
https://github.com/mepox/fitbuddy/blob/b911c38ae8f614682bfb996f49eaed03cb66c197/src/main/java/app/fitbuddy/controller/crud/ExerciseController.java#L45
https://github.com/mepox/fitbuddy/blob/b911c38ae8f614682bfb996f49eaed03cb66c197/src/main/java/app/fitbuddy/controller/crud/ExerciseController.java#L55
https://github.com/mepox/fitbuddy/blob/b911c38ae8f614682bfb996f49eaed03cb66c197/src/main/java/app/fitbuddy/controller/crud/ExerciseController.java#L68

**Comment by cerrussell** [comment]
@mepox I have created a pr for this.
