### ISSUE TITLE
Use the built-in formatting to construct this arguments in `HistoryController.java`

### ISSUE THREAD

**Issue by mepox** [mepox/fitbuddy#21]
[Link to Sonar issue](https://sonarcloud.io/project/issues?fileUuids=AYQT581YwxsCzz419tBZ&resolved=false&rules=java%3AS2629&severities=MAJOR&id=fitbuddy-app&open=AYQT58_GwxsCzz419tCX)

Compliant Solution example:
`logger.info("The message text here: {}", historyDto);`

https://github.com/mepox/fitbuddy/blob/f40fdaaee61ad336976498fce4b6a5668d5bbcda/src/main/java/com/laszlojanku/fitbuddy/operation/controller/HistoryController.java#L50

https://github.com/mepox/fitbuddy/blob/f40fdaaee61ad336976498fce4b6a5668d5bbcda/src/main/java/com/laszlojanku/fitbuddy/operation/controller/HistoryController.java#L67

https://github.com/mepox/fitbuddy/blob/f40fdaaee61ad336976498fce4b6a5668d5bbcda/src/main/java/com/laszlojanku/fitbuddy/operation/controller/HistoryController.java#L81

https://github.com/mepox/fitbuddy/blob/f40fdaaee61ad336976498fce4b6a5668d5bbcda/src/main/java/com/laszlojanku/fitbuddy/operation/controller/HistoryController.java#L94

**Comment by haseeb-xd** [comment]
I wanna work on this issue, please assign me
