### ISSUE TITLE
Use the built-in formatting to construct this arguments in `LoginController.java`

### ISSUE THREAD

**Issue by mepox** [mepox/fitbuddy#29]
[Link to Sonar issue](https://sonarcloud.io/project/issues?issues=AYQT58-wwxsCzz419tCL&open=AYQT58-wwxsCzz419tCL&id=fitbuddy-app)

Compliant Solution example:
`logger.info("The message text here: {}", loginDto);`

https://github.com/mepox/fitbuddy/blob/80ea406b0b0eb75298b83e0a0c18be4bbbeb4efe/src/main/java/com/laszlojanku/fitbuddy/operation/controller/LoginController.java#L30

**Comment by haseeb-xd** [comment]
working
