### ISSUE TITLE
Use the built-in formatting to construct this arguments in `RegisterController.java`

### ISSUE THREAD

**Issue by mepox** [mepox/fitbuddy#31]
[Link to Sonar issue](https://sonarcloud.io/project/issues?issues=AYQT58_AwxsCzz419tCV&open=AYQT58_AwxsCzz419tCV&id=fitbuddy-app)

Compliant Solution example:
`logger.info("The message text here: {}", registerDto);`

https://github.com/mepox/fitbuddy/blob/cb2be799c9b22df199e3e4983f6db89b2e92478d/src/main/java/com/laszlojanku/fitbuddy/operation/controller/RegisterController.java#L32

**Comment by haseeb-xd** [comment]
working
