### ISSUE TITLE
Change the visibility of this constructor to "protected" in `GenericCrudService.java`

### ISSUE THREAD

**Issue by mepox** [mepox/fitbuddy#66]
[Sonar link issue](https://sonarcloud.io/project/issues?issues=AYQT58_wwxsCzz419tCm&open=AYQT58_wwxsCzz419tCm&id=fitbuddy-app)

https://github.com/mepox/fitbuddy/blob/06e709035af18062e0f1e7e1d4d72b27be4cf0be/src/main/java/com/laszlojanku/fitbuddy/jpa/service/GenericCrudService.java#L12

**Comment by SwethaTamatam** [comment]
Hi @mepox I would like to work on this issue.
